# System Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.1
loader_version=0.18.4
# Use the remap-specific Loom ID for obfuscated versions
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=name.modid
archives_base_name=dozenium

# Dependencies
fabric_version=0.144.1+26.1
# Yarn mappings are still officially supported for this version
modmenu_version=18.0.0-beta.1
